config/routes.rb
Socialboard::Application.routes.draw do
  resources :boards

  root :to => "home#index"
  match "present", to: "boards#present", via: :all
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  subtitle   :string(255)
#  autoshow   :boolean
#  delay      :integer
#  repeat     :boolean
#  curated    :boolean
#  created_at :datetime
#  updated_at :datetime
#  keywords   :text             default("[]"), not null
#  blacklist  :text             default("[]"), not null
#

class Board < ActiveRecord::Base
  serialize :keywords, JSON
  serialize :blacklist, JSON

  def keywords_list=(values)
    self.keywords = values.split(/,\s*/)
  end

  def keywords_list
    self.keywords.join(", ")
  end

  def blacklist_list=(values)
    self.blacklist = values.split(/,\s*/)
  end

  def blacklist_list
    self.blacklist.join(", ")
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  name                   :string(255)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  def present
    render layout: 'presentation'
  end

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render action: 'show', status: :created, location: @board }
      else
        format.html { render action: 'new' }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:title, :subtitle, :keywords_list, :blacklist_list, :autoshow, :delay, :repeat, :curated)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_form.html.slim
= simple_form_for(@board) do |f|
  = f.error_notification

  .form-inputs
    .row
      = f.input :title
    .row 
      = f.input :subtitle
    .row
      = f.input :keywords_list, as: :text
    .row
      = f.input :blacklist_list, as: :text
    .row
      = f.input :delay, label: "Delay in Seconds", collection: 5..60, wrapper_html: { class: "large-3 columns" }
      = f.input :autoshow, label: "Show Images", wrapper_html: { class: "large-3 columns" }
      = f.input :repeat, label: "Repeat Continuously", wrapper_html: { class: "large-3 columns" }
      = f.input :curated, wrapper_html: { class: "large-3 columns" }
      
  .form-actions
    = f.button :submit

app/views/boards/edit.html.slim
h1 Editing board

== render 'form'

= link_to 'Show', @board
'|
= link_to 'Back', boards_path

app/views/boards/index.html.slim
h1 Listing SocialBoards

table
  thead
    tr
      th Title
      th Subtitle
      th Autoshow
      th Delay
      th Repeat
      th Curated
      th
      th
      th

  tbody
    - @boards.each do |board|
      tr
        td = board.title
        td = board.subtitle
        td = board.autoshow
        td = board.delay
        td = board.repeat
        td = board.curated
        td = link_to 'Show', board
        td = link_to 'Edit', edit_board_path(board)
        td = link_to 'Destroy', board, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Board', new_board_path

app/views/boards/new.html.slim
h1 New SocialBoard

== render 'form'

= link_to 'Back', boards_path

app/views/boards/present.html.slim
div.slide-show
  div.slide
    h1 Wow, Open Source NOLA is awesome, but the really amazing part is @GantLaborde's beautiful face.
    h2 via @Bryanjos

app/views/boards/show.html.slim
p#notice = notice

p
  strong Title:
  = @board.title
p
  strong Subtitle:
  = @board.subtitle
p
  strong Keywords:
  = @board.keywords_list
p
  strong Blacklist:
  = @board.blacklist_list
p
  strong Autoshow:
  = @board.autoshow
p
  strong Delay:
  = @board.delay
p
  strong Repeat:
  = @board.repeat
p
  strong Curated:
  = @board.curated

= link_to 'Edit', edit_board_path(@board)
'|
= link_to 'Back', boards_path

app/views/home/index.html.slim
h3 Home

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Zurb Foundation
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div[class="alert-box round #{name.to_s == 'notice' ? 'success' : 'alert'}" data-alert]
      = content_tag :div, msg
      a.close[href="#"]
        | ×

app/views/layouts/_navigation.html.slim
/ navigation styled for Zurb Foundation 5
nav.top-bar[data-topbar]
  ul.title-area
    li.name
      = link_to 'Home', root_path
    li.toggle-topbar.menu-icon
      a[href="#"]
        Menu
  .top-bar-section
    ul
      == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
  <li><%= link_to 'SocialBoards', boards_path %></li>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Socialboard'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Socialboard'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    / Modernizr is required for Zurb Foundation
    == javascript_include_tag 'vendor/modernizr'
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield

app/views/layouts/presentation.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Socialboard'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Socialboard'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    / Modernizr is required for Zurb Foundation
    == javascript_include_tag 'vendor/modernizr'
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    header
      p Header Stuff
    .social_block
      == render 'layouts/messages'
      == yield

app/views/users/index.html.slim
h3 Users
ul.users
  - @users.each do |user|
    li
      = link_to user.name, user
      | signed up #{user.created_at.to_date}

app/views/users/show.html.slim
h3 User
p
  | User: #{@user.name}
p
  | Email: #{@user.email if @user.email}
= link_to 'Edit account', edit_user_path